# Generated by Django 3.2.9 on 2021-12-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Choice',
        ),
    ]
